#!/bin/sh

# This control script should be linked from /etc/init.d

### BEGIN INIT INFO
# Provides:          paster application instance
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of paster app
# Description:       starts instance of paster app using start-stop-daemon
### END INIT INFO

############### EDIT ME ##################
DAEMON=/usr/bin/paster
LOGFILE="/var/log/paster.log"
#DAEMON_OPTS=" serve --log-file $LOGFILE --reload production.ini"
DAEMON_OPTS=" serve --log-file $LOGFILE --reload development.ini"
RUN_AS=root
APP_PATH=/home/jwiggins/amat/trunk/server
PID_FILE=/var/run/paster.pid
NAME="paster"
############### END EDIT ME ##################

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo -n "Starting $NAME: "
        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        echo "done."
        ;;

  stop)
        echo -n "Stopping $NAME: "
        start-stop-daemon --stop --pidfile $PID_FILE
        echo "done."
        ;;

  restart|force-reload)
        echo -n "Restarting $NAME: "
        start-stop-daemon --stop --pidfile $PID_FILE
        sleep 1
        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        echo "done."
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0

